export enum IpcEvents {
  SYNC_SOI_GET_FILE_CONTENT = 'SYNC_SOI_GET_FILE_CONTENT',
  SYNC_SOI_UPDATE_FILE_CONTENT = 'SYNC_SOI_UPDATE_FILE_CONTENT',
  SYNC_SOI_RESET_TO_DEFAULT = 'SYNC_SOI_RESET_TO_DEFAULT',
  SOI_CONSOLE_LOG = 'SOI_CONSOLE_LOG'
}

export const ipcMainEvents = [
  IpcEvents.SYNC_SOI_GET_FILE_CONTENT,
  IpcEvents.SYNC_SOI_UPDATE_FILE_CONTENT,
  IpcEvents.SYNC_SOI_RESET_TO_DEFAULT
];

export const ipcRendererEvents = [
  IpcEvents.SOI_CONSOLE_LOG
];

export const WEBCONTENTS_READY_FOR_IPC_SIGNAL = 'WEBCONTENTS_READY_FOR_IPC_SIGNAL';
